// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTiqucuIi0_fW5tGeLgPERgXIUb9puRiQ',
    appId: '1:443282632703:web:5827c4ebae74fe4917c1ca',
    messagingSenderId: '443282632703',
    projectId: 'irfan-khan-53340',
    authDomain: 'irfan-khan-53340.firebaseapp.com',
    storageBucket: 'irfan-khan-53340.firebasestorage.app',
    measurementId: 'G-DBRHMK6BPB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDROQZxegO_wrmHTepvqiiMk3d1DB4C27M',
    appId: '1:443282632703:android:aafcf59c0b11be1317c1ca',
    messagingSenderId: '443282632703',
    projectId: 'irfan-khan-53340',
    storageBucket: 'irfan-khan-53340.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAg6r_JcNt09coXrYoOn-nfRAORG3vak4',
    appId: '1:443282632703:ios:a4e1a75fbedfa50217c1ca',
    messagingSenderId: '443282632703',
    projectId: 'irfan-khan-53340',
    storageBucket: 'irfan-khan-53340.firebasestorage.app',
    iosBundleId: 'com.example.meetWithDev',
  );
}
